version: '2'

services:
    pemiweb:
        image: fake-web-image
        container_name: fake-web
        build:
          context: ./.docker/nginx/
          dockerfile: ./Dockerfile
        environment:
          - VIRTUAL_PORT=80
        restart: always
        volumes:
          - './src:/usr/share/nginx/html:Z'
        ports:
          - '80:80'

networks:
  default:
    external:
      name: nginx-proxy
